# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@arsonar/client-0.4.0" = {
      name = "_at_arsonar_slash_client";
      packageName = "@arsonar/client";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@arsonar/client/-/client-0.4.0.tgz";
        sha512 = "1p578aZCFoEfur63Xe2XSd5qH4LLGy1SmY1uI7YQ6OsINWjYFTZX8ybyXM5N7T1rO9DcEYLGxwJ5H65kse2oMw==";
      };
    };
    "@arsonar/common-0.4.0" = {
      name = "_at_arsonar_slash_common";
      packageName = "@arsonar/common";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@arsonar/common/-/common-0.4.0.tgz";
        sha512 = "nNDFWBgrTGK31oG8+iLAsi+Y1VY2sphkaR0ESuPdAFnKq6+5k80j7waOga8B76yCCn4CPVxbtFv3arie+MciaA==";
      };
    };
    "aggregate-error-3.1.0" = {
      name = "aggregate-error";
      packageName = "aggregate-error";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aggregate-error/-/aggregate-error-3.1.0.tgz";
        sha512 = "4I7Td01quW/RpocfNayFdFVk1qSuoh0E7JrbRJ16nH01HhKFQ88INq9Sd+nd72zqRySlr9BmDA8xlEJ6vJMrYA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "arrify-2.0.1" = {
      name = "arrify";
      packageName = "arrify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arrify/-/arrify-2.0.1.tgz";
        sha512 = "3duEwti880xqi4eAMN8AyR4a0ByT90zoYdLlevfrvU43vb0YZwZVfxOgxWrLXXXpyugL0hNZc9G6BiB5B3nUug==";
      };
    };
    "assign-symbols-1.0.0" = {
      name = "assign-symbols";
      packageName = "assign-symbols";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assign-symbols/-/assign-symbols-1.0.0.tgz";
        sha1 = "59667f41fadd4f20ccbc2bb96b8d4f7f78ec0367";
      };
    };
    "async-exit-hook-2.0.1" = {
      name = "async-exit-hook";
      packageName = "async-exit-hook";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-exit-hook/-/async-exit-hook-2.0.1.tgz";
        sha512 = "NW2cX8m1Q7KPA7a5M2ULQeZ2wR5qI5PAbw5L0UOMxdioVk9PMZ0h1TmyZEkPYrCvYjDlFICusOu1dlEKAAeXBw==";
      };
    };
    "atomic-sleep-1.0.0" = {
      name = "atomic-sleep";
      packageName = "atomic-sleep";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/atomic-sleep/-/atomic-sleep-1.0.0.tgz";
        sha512 = "kNOjDqAh7px0XWNI+4QbzoiR/nTkHAWNud2uvnJquD1/x5a7EQZMJT0AczqK0Qn67oY/TTQ1LbUKajZpp3I9tQ==";
      };
    };
    "base32-encode-1.2.0" = {
      name = "base32-encode";
      packageName = "base32-encode";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base32-encode/-/base32-encode-1.2.0.tgz";
        sha512 = "cHFU8XeRyx0GgmoWi5qHMCVRiqU6J3MHWxVgun7jggCBUpVzm1Ir7M9dYr2whjSNc3tFeXfQ/oZjQu/4u55h9A==";
      };
    };
    "batch-0.6.1" = {
      name = "batch";
      packageName = "batch";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/batch/-/batch-0.6.1.tgz";
        sha1 = "dc34314f4e679318093fc760272525f94bf25c16";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "clean-stack-2.2.0" = {
      name = "clean-stack";
      packageName = "clean-stack";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-stack/-/clean-stack-2.2.0.tgz";
        sha512 = "4diC9HaTE+KRAMWhDhrGOECgWZxoevMc5TlkObMqNSsVU62PYzXZ/SMTjzyGAFF1YusgxGcSWTEXBhp0CPwQ1A==";
      };
    };
    "codecs-2.2.0" = {
      name = "codecs";
      packageName = "codecs";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/codecs/-/codecs-2.2.0.tgz";
        sha512 = "+xi2ENsvchtUNa8oBUU58gHgmyN6BEEeZ8NIEgeQ0XnC+AoyihivgZYe+OOiNi+fLy/NUowugwV5gP8XWYDm0Q==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "commander-5.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-5.1.0.tgz";
        sha512 = "P0CysNDQ7rtVw4QIQtm+MRxV66vKFSvlsQvGYXZWR3qFU0jlMKHZZZgw8e+8DSah4UDKMqnknRDQz+xuQXQ/Zg==";
      };
    };
    "cross-spawn-7.0.3" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz";
        sha512 = "iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==";
      };
    };
    "crypto-hash-1.3.0" = {
      name = "crypto-hash";
      packageName = "crypto-hash";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-hash/-/crypto-hash-1.3.0.tgz";
        sha512 = "lyAZ0EMyjDkVvz8WOeVnuCPvKVBXcMv1l5SVqO1yC7PzTwrD/pPje/BIRbWhMoPe436U+Y2nD7f5bFx0kt+Sbg==";
      };
    };
    "debug-4.3.2" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.2.tgz";
        sha512 = "mOp8wKcvj7XxC78zLgw/ZA+6TSgkoE2C/ienthhRD298T7UNwAg9diBpLRxC0mOezLl4B0xV7M0cCO6P/O0Xhw==";
      };
    };
    "define-property-2.0.2" = {
      name = "define-property";
      packageName = "define-property";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-2.0.2.tgz";
        sha512 = "jwK2UV4cnPpbcG7+VRARKTZPUWowwXA8bzH5NP6ud0oeAxyYPuGZUAC7hMugpCdz4BeSZl2Dl9k66CHJ/46ZYQ==";
      };
    };
    "encoding-0.1.13" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz";
        sha512 = "ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "eventsource-git://github.com/frando/eventsource" = {
      name = "eventsource";
      packageName = "eventsource";
      version = "1.0.7";
      src = fetchgit {
        url = "git://github.com/frando/eventsource";
        rev = "ab70c54fa12f27dbb213780d24bf753a23933ed9";
        sha256 = "3637e39a1881089ee3afa35025917a735059215b834c5864f83bbdfba3ebcc1c";
      };
    };
    "execa-3.4.0" = {
      name = "execa";
      packageName = "execa";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-3.4.0.tgz";
        sha512 = "r9vdGQk4bmCuK1yKQu1KTwcT2zwfWdbdaXfCtAh+5nU/4fSX+JAb7vZGvI5naJrQlvONrEB20jeruESI69530g==";
      };
    };
    "execa-5.1.1" = {
      name = "execa";
      packageName = "execa";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-5.1.1.tgz";
        sha512 = "8uSpZZocAZRBAPIEINJj3Lo9HyGitllczc27Eh5YYojjMFMn8yHMDMaUHE2Jqfq05D/wucwI4JGURyXt1vchyg==";
      };
    };
    "extend-shallow-3.0.2" = {
      name = "extend-shallow";
      packageName = "extend-shallow";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-3.0.2.tgz";
        sha1 = "26a71aaf073b39fb2127172746131c2704028db8";
      };
    };
    "fast-fifo-1.0.0" = {
      name = "fast-fifo";
      packageName = "fast-fifo";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-fifo/-/fast-fifo-1.0.0.tgz";
        sha512 = "4VEXmjxLj7sbs8J//cn2qhRap50dGzF5n8fjay8mau+Jn4hxSeR3xPFwxMaQq/pDaq7+KQk0PAbC2+nWDkJrmQ==";
      };
    };
    "fast-redact-3.0.1" = {
      name = "fast-redact";
      packageName = "fast-redact";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-redact/-/fast-redact-3.0.1.tgz";
        sha512 = "kYpn4Y/valC9MdrISg47tZOpYBNoTXKgT9GYXFpHN/jYFs+lFkPoisY+LcBODdKVMY96ATzvzsWv+ES/4Kmufw==";
      };
    };
    "fast-safe-stringify-2.0.8" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.0.8.tgz";
        sha512 = "lXatBjf3WPjmWD6DpIZxkeSsCOwqI0maYMpgDlx8g4U2qi4lbjA9oH/HD2a87G+KfsUmo5WbJFmqBZlPxtptag==";
      };
    };
    "find-process-1.4.4" = {
      name = "find-process";
      packageName = "find-process";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-process/-/find-process-1.4.4.tgz";
        sha512 = "rRSuT1LE4b+BFK588D2V8/VG9liW0Ark1XJgroxZXI0LtwmQJOb490DvDYvbm+Hek9ETFzTutGfJ90gumITPhQ==";
      };
    };
    "fkill-7.2.1" = {
      name = "fkill";
      packageName = "fkill";
      version = "7.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fkill/-/fkill-7.2.1.tgz";
        sha512 = "eN9cmsIlRdq06wu3m01OOEgQf5Xh/M7REm0jfZ4eL3V3XisjXzfRq3iyqtKS+FhO6wB36FvWRiRGdeSx5KpLAQ==";
      };
    };
    "flatstr-1.0.12" = {
      name = "flatstr";
      packageName = "flatstr";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/flatstr/-/flatstr-1.0.12.tgz";
        sha512 = "4zPxDyhCyiN2wIAtSLI6gc82/EjqZc1onI4Mz/l0pWrAlsSfYH/2ZIcU+e3oA2wDwbzIWNKwa23F8rh6+DRWkw==";
      };
    };
    "get-stream-5.2.0" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-5.2.0.tgz";
        sha512 = "nBF+F1rAZVCu/p7rjzgA+Yb4lfYXrpl7a6VmJrU8wF9I1CKvP/QwPNZHnOlwbTkY6dvtFIzFMSyQXbLoTQPRpA==";
      };
    };
    "get-stream-6.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz";
        sha512 = "ts6Wi+2j3jQjqi70w5AlN8DFnkSwC+MqmxEzdEALB2qXZYV3X/b1CTfgPLGJNMeAWxdPfU8FO1ms3NUfaHCPYg==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "human-signals-1.1.1" = {
      name = "human-signals";
      packageName = "human-signals";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/human-signals/-/human-signals-1.1.1.tgz";
        sha512 = "SEQu7vl8KjNL2eoGBLF3+wAjpsNfA9XMlXAYj/3EdaNfAlxKthD1xjEQfGOUhllCGGJVNY34bRr6lPINhNjyZw==";
      };
    };
    "human-signals-2.1.0" = {
      name = "human-signals";
      packageName = "human-signals";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/human-signals/-/human-signals-2.1.0.tgz";
        sha512 = "B4FFZ6q/T2jhhksgkbEW3HBvWIfDW85snkQgawt07S7J5QXTk6BkNV+0yAeZrM5QpMAdYlocGoljn0sJ/WQkFw==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "indent-string-4.0.0" = {
      name = "indent-string";
      packageName = "indent-string";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/indent-string/-/indent-string-4.0.0.tgz";
        sha512 = "EdDDZu4A2OyIK7Lr/2zG+w5jmbuk1DVBnEwREQvBzspBJkCEbRa8GxU1lghYcaGJCnRWibjDXlq779X1/y5xwg==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "inspect-custom-symbol-1.1.1" = {
      name = "inspect-custom-symbol";
      packageName = "inspect-custom-symbol";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inspect-custom-symbol/-/inspect-custom-symbol-1.1.1.tgz";
        sha512 = "GOucsp9EcdlLdhPUyOTvQDnbFJtp2WBWZV1Jqe+mVnkJQBL3w96+fB84C+JL+EKXOspMdB0eMDQPDp5w9fkfZA==";
      };
    };
    "is-accessor-descriptor-1.0.0" = {
      name = "is-accessor-descriptor";
      packageName = "is-accessor-descriptor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-accessor-descriptor/-/is-accessor-descriptor-1.0.0.tgz";
        sha512 = "m5hnHTkcVsPfqx3AKlyttIPb7J+XykHvJP2B9bZDjlhLIoEq4XoK64Vg7boZlVWYK6LUY94dYPEE7Lh0ZkZKcQ==";
      };
    };
    "is-buffer-2.0.5" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-2.0.5.tgz";
        sha512 = "i2R6zNFDwgEHJyQUtJEk0XFi1i0dPFn/oqjK3/vPCcDeJvW5NQ83V8QbicfF1SupOaB0h8ntgBC2YiE7dfyctQ==";
      };
    };
    "is-data-descriptor-1.0.0" = {
      name = "is-data-descriptor";
      packageName = "is-data-descriptor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-descriptor/-/is-data-descriptor-1.0.0.tgz";
        sha512 = "jbRXy1FmtAoCjQkVmIVYwuuqDFUbaOeDjmed1tOGPrsMhtJA4rD9tkgA0F1qJ3gRFRXcHYVkdeaP50Q5rE/jLQ==";
      };
    };
    "is-descriptor-1.0.2" = {
      name = "is-descriptor";
      packageName = "is-descriptor";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-descriptor/-/is-descriptor-1.0.2.tgz";
        sha512 = "2eis5WqQGV7peooDyLmNEPUrps9+SXX5c9pL3xEB+4e9HnGuDa7mB7kHxHw4CbqS9k1T2hOH3miL8n8WtiYVtg==";
      };
    };
    "is-docker-2.2.1" = {
      name = "is-docker";
      packageName = "is-docker";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-docker/-/is-docker-2.2.1.tgz";
        sha512 = "F+i2BKsFrH66iaUFc0woD8sLy8getkwTwtOBjvs56Cx4CgJDeKQeqfz8wAYiSb8JOprWhHH5p77PbmYCvvUuXQ==";
      };
    };
    "is-extendable-1.0.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-1.0.1.tgz";
        sha512 = "arnXMxT1hhoKo9k1LZdmlNyJdDDfy2v0fXjFlmok4+i8ul/6WlbVge9bhM74OpNPQPMGUToDtz+KXa1PneJxOA==";
      };
    };
    "is-plain-object-2.0.4" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-2.0.4.tgz";
        sha512 = "h5PpgXkWitc38BBMYawTYMWJHFZJVnBquFE57xFpjB8pJFiF6gZ+bU+WyI/yqXiFR5mdLsgYNaPe8uao6Uv9Og==";
      };
    };
    "is-running-2.1.0" = {
      name = "is-running";
      packageName = "is-running";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-running/-/is-running-2.1.0.tgz";
        sha1 = "30a73ff5cc3854e4fc25490809e9f5abf8de09e0";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "is-stream-2.0.1" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-2.0.1.tgz";
        sha512 = "hFoiJiTl63nn+kstHGBtewWSKnQLpyb155KHheA1l39uvtO9nWIop1p3udqPcUd/xbF1VLMO4n7OI6p7RbngDg==";
      };
    };
    "is-wsl-2.2.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-2.2.0.tgz";
        sha512 = "fKzAra0rGJUUBwGBgNkHZuToZcn+TtXHpeCgmkMJMMYx1sQDYaCSyjJBSCa2nH1DGm7s3n1oBnohoVTBaN7Lww==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha1 = "4e431e92b11a9731636aa1f9c8d1ccbcfdab78df";
      };
    };
    "isomorphic-fetch-2.2.1" = {
      name = "isomorphic-fetch";
      packageName = "isomorphic-fetch";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-2.2.1.tgz";
        sha1 = "611ae1acf14f5e81f729507472819fe9733558a9";
      };
    };
    "js-yaml-3.14.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz";
        sha512 = "okMH7OXXJ7YrN9Ok3/SXrnu4iX9yOk+25nqX4imS2npuvTYDmo/QEZoqwZkYaIDk3jVvBOTOIEgEhaLOynBS9g==";
      };
    };
    "kind-of-6.0.3" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.3.tgz";
        sha512 = "dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==";
      };
    };
    "little-process-box-0.2.3" = {
      name = "little-process-box";
      packageName = "little-process-box";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/little-process-box/-/little-process-box-0.2.3.tgz";
        sha512 = "/3H2RsLsXVCOaDstDQSo9JmapjRoc4Rpba/L2uBVe+RWZxiK69fbzxVC5XemP2g92+OsaU83eQY6RQV+wlX3XA==";
      };
    };
    "merge-stream-2.0.0" = {
      name = "merge-stream";
      packageName = "merge-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
        sha512 = "abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "mutexify-1.3.1" = {
      name = "mutexify";
      packageName = "mutexify";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mutexify/-/mutexify-1.3.1.tgz";
        sha512 = "nU7mOEuaXiQIB/EgTIjYZJ7g8KqMm2D8l4qp+DqA4jxWOb/tnb1KEoqp+tlbdQIDIAiC1i7j7X/3yHDFXLxr9g==";
      };
    };
    "nanoassert-2.0.0" = {
      name = "nanoassert";
      packageName = "nanoassert";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoassert/-/nanoassert-2.0.0.tgz";
        sha512 = "7vO7n28+aYO4J+8w96AzhmU8G+Y/xpPDJz/se19ICsqj/momRbb9mh9ZUtkoJ5X3nTnPdhEJyc0qnM6yAsHBaA==";
      };
    };
    "nanoguard-1.3.0" = {
      name = "nanoguard";
      packageName = "nanoguard";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoguard/-/nanoguard-1.3.0.tgz";
        sha512 = "K/ON5wyflyPyZskdeT3m7Y2gJVkm3QLdKykMCquAbK8A2erstyMpZUc3NG8Nz5jKdfatiYndONrlmLF8+pGl+A==";
      };
    };
    "nanoprocess-0.8.5" = {
      name = "nanoprocess";
      packageName = "nanoprocess";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoprocess/-/nanoprocess-0.8.5.tgz";
        sha512 = "PV1jcEZIwnSdMWUfmq5adDvKpn2n3Q6dCKchOGl6JBSJTFyBL/pkVKOXLTKKWQWnhY6fEAITR+KN7BezzLKM5A==";
      };
    };
    "nanoresource-1.3.0" = {
      name = "nanoresource";
      packageName = "nanoresource";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoresource/-/nanoresource-1.3.0.tgz";
        sha512 = "OI5dswqipmlYfyL3k/YMm7mbERlh4Bd1KuKdMHpeoVD1iVxqxaTMKleB4qaA2mbQZ6/zMNSxCXv9M9P/YbqTuQ==";
      };
    };
    "nanoresource-pool-0.3.1" = {
      name = "nanoresource-pool";
      packageName = "nanoresource-pool";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoresource-pool/-/nanoresource-pool-0.3.1.tgz";
        sha512 = "0URxLwp6NNi8W3vz0AvN8kxJECI9CGk1y4bLNrSj4H6PvAt5HzBjT22KU7z3uEujGAjvdKbAz4LcBL0GITjZFg==";
      };
    };
    "node-fetch-1.7.3" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-1.7.3.tgz";
        sha512 = "NhZ4CsKx7cYm2vSrBAr2PvFOe6sWDf0UYLRqA6svUYg7+/TSfVAu49jYC4BvQ4Sms9SZgdqGBgroqfDhJdTyKQ==";
      };
    };
    "npm-run-path-4.0.1" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-4.0.1.tgz";
        sha512 = "S48WzZW777zhNIrn7gxOlISNAqi9ZC/uQFnRdbeIHhZhCA6UqpkOT8T1G7BvfdgP4Er8gF4sUbaS0i7QvIfCWw==";
      };
    };
    "object-path-0.11.5" = {
      name = "object-path";
      packageName = "object-path";
      version = "0.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-path/-/object-path-0.11.5.tgz";
        sha512 = "jgSbThcoR/s+XumvGMTMf81QVBmah+/Q7K7YduKeKVWL7N111unR2d6pZZarSk6kY/caeNxUDyxOvMWyzoU2eg==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "open-7.4.2" = {
      name = "open";
      packageName = "open";
      version = "7.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-7.4.2.tgz";
        sha512 = "MVHddDVweXZF3awtlAS+6pgKLlm/JgxZ90+/NBurBoQctVOOB/zDdVjcyPzQ+0laDGbsWgrRkflI65sQeOgT9Q==";
      };
    };
    "original-1.0.2" = {
      name = "original";
      packageName = "original";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/original/-/original-1.0.2.tgz";
        sha512 = "hyBVl6iqqUOJ8FqRe+l/gS8H+kKYjrEndd5Pm1MfBtsEKA038HkkdbAl/72EAXGyonD/PFsvmVG+EvcIpliMBg==";
      };
    };
    "p-finally-2.0.1" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-2.0.1.tgz";
        sha512 = "vpm09aKwq6H9phqRQzecoDpD8TmVyGw70qmWlyq5onxY7tqyTTFVvxMykxQSQKILBSFlbXpypIw2T1Ml7+DDtw==";
      };
    };
    "parse-dat-url-3.0.3" = {
      name = "parse-dat-url";
      packageName = "parse-dat-url";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-dat-url/-/parse-dat-url-3.0.3.tgz";
        sha512 = "7a/rNzaZqhOHlZ1rwxz4xmERI47PpnAkuqbnkne9IH91D/pQ2T0+g5jK9kVUCp+jKHYRA0j4kbsyaluiF9XoaA==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "pid-port-0.1.1" = {
      name = "pid-port";
      packageName = "pid-port";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pid-port/-/pid-port-0.1.1.tgz";
        sha512 = "boqPJtSgZC6KOgXKNPC+/XR3xwVtpOtaLa7JLcdf8jfVe0ZM2TwllBXxxLUO8GQbOLJ4/hEtf2+L1QCKbaoHUg==";
      };
    };
    "pidtree-0.3.1" = {
      name = "pidtree";
      packageName = "pidtree";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pidtree/-/pidtree-0.3.1.tgz";
        sha512 = "qQbW94hLHEqCg7nhby4yRC7G2+jYHY4Rguc2bjw7Uug4GIJuu1tvf2uHaZv5Q8zdt+WKJ6qK1FOI6amaWUo5FA==";
      };
    };
    "pidusage-2.0.21" = {
      name = "pidusage";
      packageName = "pidusage";
      version = "2.0.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/pidusage/-/pidusage-2.0.21.tgz";
        sha512 = "cv3xAQos+pugVX+BfXpHsbyz/dLzX+lr44zNMsYiGxUw+kV5sgQCIcLd1z+0vq+KyC7dJ+/ts2PsfgWfSC3WXA==";
      };
    };
    "pino-6.13.0" = {
      name = "pino";
      packageName = "pino";
      version = "6.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino/-/pino-6.13.0.tgz";
        sha512 = "mRXSTfa34tbfrWqCIp1sUpZLqBhcoaGapoyxfEwaWwJGMpLijlRdDKIQUyvq4M3DUfFH5vEglwSw8POZYwbThA==";
      };
    };
    "pino-std-serializers-3.2.0" = {
      name = "pino-std-serializers";
      packageName = "pino-std-serializers";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pino-std-serializers/-/pino-std-serializers-3.2.0.tgz";
        sha512 = "EqX4pwDPrt3MuOAAUBMU0Tk5kR/YcCM5fNPEzgCO2zJ5HfX0vbiH9HbJglnyeQsN96Kznae6MWD47pZB5avTrg==";
      };
    };
    "pretty-hash-1.0.1" = {
      name = "pretty-hash";
      packageName = "pretty-hash";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pretty-hash/-/pretty-hash-1.0.1.tgz";
        sha1 = "16e0579188def56bdb565892bcd05a5d65324807";
      };
    };
    "process-exists-4.1.0" = {
      name = "process-exists";
      packageName = "process-exists";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-exists/-/process-exists-4.1.0.tgz";
        sha512 = "BBJoiorUKoP2AuM5q/yKwIfT1YWRHsaxjW+Ayu9erLhqKOfnXzzVVML0XTYoQZuI1YvcWKmc1dh06DEy4+KzfA==";
      };
    };
    "ps-list-6.3.0" = {
      name = "ps-list";
      packageName = "ps-list";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ps-list/-/ps-list-6.3.0.tgz";
        sha512 = "qau0czUSB0fzSlBOQt0bo+I2v6R+xiQdj78e1BR/Qjfl5OHWJ/urXi8+ilw1eHe+5hSeDI1wrwVTgDp2wst4oA==";
      };
    };
    "ps-list-7.2.0" = {
      name = "ps-list";
      packageName = "ps-list";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ps-list/-/ps-list-7.2.0.tgz";
        sha512 = "v4Bl6I3f2kJfr5o80ShABNHAokIgY+wFDTQfE+X3zWYgSGQOCBeYptLZUpoOALBqO5EawmDN/tjTldJesd0ujQ==";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "querystringify-2.2.0" = {
      name = "querystringify";
      packageName = "querystringify";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystringify/-/querystringify-2.2.0.tgz";
        sha512 = "FIqgj2EUvTa7R50u0rGsyTftzjYmv/a3hO345bZNrqabNqjtgiDMgmo4mkUjd+nzU5oF3dClKqFIPUKybUyqoQ==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "queue-tick-1.0.0" = {
      name = "queue-tick";
      packageName = "queue-tick";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-tick/-/queue-tick-1.0.0.tgz";
        sha512 = "ULWhjjE8BmiICGn3G8+1L9wFpERNxkf8ysxkAer4+TFdRefDaXOCV5m92aMB9FtBVmn/8sETXLXY6BfW7hyaWQ==";
      };
    };
    "quick-format-unescaped-4.0.3" = {
      name = "quick-format-unescaped";
      packageName = "quick-format-unescaped";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-format-unescaped/-/quick-format-unescaped-4.0.3.tgz";
        sha512 = "MaL/oqh02mhEo5m5J2rwsVL23Iw2PEaGVHgT2vFt8AAsr0lfvQA5dpXo9TPu0rz7tSBdUPgkbam0j/fj5ZM8yg==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "regex-not-1.0.2" = {
      name = "regex-not";
      packageName = "regex-not";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regex-not/-/regex-not-1.0.2.tgz";
        sha512 = "J6SDjUgDxQj5NusnOtdFxDwN/+HWykR8GELwctJ7mdqhcyy1xEc4SRFHUXvxTp661YaVKAjfRLZ9cCqS6tn32A==";
      };
    };
    "requires-port-1.0.0" = {
      name = "requires-port";
      packageName = "requires-port";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/requires-port/-/requires-port-1.0.0.tgz";
        sha1 = "925d2601d39ac485e091cf0da5c6e694dc3dcaff";
      };
    };
    "ret-0.1.15" = {
      name = "ret";
      packageName = "ret";
      version = "0.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.1.15.tgz";
        sha512 = "TTlYpa+OL+vMMNG24xSlQGEJ3B/RzEfUlLct7b5G/ytav+wPrplCpVMFuwzXbkecJrb6IYo1iFb0S9v37754mg==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safe-regex-1.1.0" = {
      name = "safe-regex";
      packageName = "safe-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex/-/safe-regex-1.1.0.tgz";
        sha1 = "40a3669f3b077d1e943d44629e157dd48023bf2e";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-3.0.3" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.3.tgz";
        sha512 = "VUJ49FC8U1OxwZLxIbTTrDvLnf/6TDgxZcK8wxR8zs13xpx7xbG60ndBlhNrFi2EMuFRoeDoJO7wthSLq42EjA==";
      };
    };
    "simple-message-channels-1.2.1" = {
      name = "simple-message-channels";
      packageName = "simple-message-channels";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-message-channels/-/simple-message-channels-1.2.1.tgz";
        sha512 = "knSr69GKW9sCjzpoy817xQelpOASUQ53TXCBcSLDKLE7GTGpUAhZzOZYrdbX2Ig//m+8AIrNp7sM7HDNHBRzXw==";
      };
    };
    "simple-rpc-protocol-0.4.1" = {
      name = "simple-rpc-protocol";
      packageName = "simple-rpc-protocol";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-rpc-protocol/-/simple-rpc-protocol-0.4.1.tgz";
        sha512 = "4iaLtR5HvKjYnPmfZUSaMNH7h63+0VDcosDoyNRRL4X4/pC5ykRb2WRdtptv214966lieRRp49myYUl8Og5Oyg==";
      };
    };
    "simple-websocket-8.1.1" = {
      name = "simple-websocket";
      packageName = "simple-websocket";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-websocket/-/simple-websocket-8.1.1.tgz";
        sha512 = "06I3cwOD5Q3LdVd6qfyDGp1U9eau9x9qniSL3b/aDgM5bsJX4nZfCuii2UCFcTfrDq0jCXF4NQ/38qeC8CJZTg==";
      };
    };
    "sonic-boom-1.4.1" = {
      name = "sonic-boom";
      packageName = "sonic-boom";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sonic-boom/-/sonic-boom-1.4.1.tgz";
        sha512 = "LRHh/A8tpW7ru89lrlkU4AszXt1dbwSjVWguGrmlxE7tawVmDBlI1PILMkXAxJTwqhgsEeTHzj36D5CmHgQmNg==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "streamx-2.11.1" = {
      name = "streamx";
      packageName = "streamx";
      version = "2.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamx/-/streamx-2.11.1.tgz";
        sha512 = "GG/cBcuwhKEu2MxJIdlFnrstgtwERx0yX0tjZUVFHmmq65ROrCEAVrfoYbNQnXdq76rH0Y/SuO9VcgW+ZPkeMQ==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-final-newline-2.0.0" = {
      name = "strip-final-newline";
      packageName = "strip-final-newline";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-2.0.0.tgz";
        sha512 = "BrpvfNAE3dcvq7ll3xVumzjKjZQ5tI1sEUIKr3Uoks0XUl45St3FlatVqef9prk4jRDzhW6WZg+3bk93y6pLjA==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "taskkill-3.1.0" = {
      name = "taskkill";
      packageName = "taskkill";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/taskkill/-/taskkill-3.1.0.tgz";
        sha512 = "5KcOFzPvd1nGFVrmB7H4+QAWVjYOf//+QTbOj0GpXbqtqbKGWVczG+rq6VhXAtdtlKLTs16NAmHRyF5vbggQ2w==";
      };
    };
    "through2-3.0.2" = {
      name = "through2";
      packageName = "through2";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-3.0.2.tgz";
        sha512 = "enaDQ4MUyP2W6ZyT6EsMzqBPZaM/avg8iuo+l2d3QCs0J+6RaqkHV/2/lOwDTueBHeJ/2LG9lrLW3d5rWPucuQ==";
      };
    };
    "to-data-view-1.1.0" = {
      name = "to-data-view";
      packageName = "to-data-view";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-data-view/-/to-data-view-1.1.0.tgz";
        sha512 = "1eAdufMg6mwgmlojAx3QeMnzB/BTVp7Tbndi3U7ftcT2zCZadjxkkmLmd97zmaxWi+sgGcgWrokmpEoy0Dn0vQ==";
      };
    };
    "to-regex-3.0.2" = {
      name = "to-regex";
      packageName = "to-regex";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex/-/to-regex-3.0.2.tgz";
        sha512 = "FWtleNAtZ/Ki2qtqej2CXTOayOH9bHDQF+Q48VpWyDXjbYxA4Yz8iDB31zXOBUlOHHKidDbqGVrTUvQMPmBGBw==";
      };
    };
    "url-parse-1.5.3" = {
      name = "url-parse";
      packageName = "url-parse";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse/-/url-parse-1.5.3.tgz";
        sha512 = "IIORyIQD9rvj0A4CLWsHkBBJuNqWpFQe224b6j9t/ABmquIS0qDU2pY6kl6AuOrL5OkCXHMCFNe1jBcuAggjvQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "varint-5.0.2" = {
      name = "varint";
      packageName = "varint";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/varint/-/varint-5.0.2.tgz";
        sha512 = "lKxKYG6H03yCZUpAGOPOsMcGxd1RHCu1iKvEHYDPmTyq2HueGhD73ssNBqqQWfvYs04G9iUFRvmAVLW20Jw6ow==";
      };
    };
    "whatwg-fetch-3.6.2" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-3.6.2.tgz";
        sha512 = "bJlen0FcuU/0EMLrdbJ7zOnW6ITZLrZMIarMUVmdKtsGvZna8vxKYaexICWPfZ8qwf9fzNq+UEIZrnSaApt6RA==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-7.5.3" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.3.tgz";
        sha512 = "kQ/dHIzuLrS6Je9+uv81ueZomEwH0qVYstcAQ4/Z93K8zeko9gtAbttJWzoC5ukqXY1PpoouV3+VSOqEAFt5wg==";
      };
    };
  };
  args = {
    name = "_at_arsonar_slash_bots";
    packageName = "@arsonar/bots";
    version = "0.4.0";
    src = ../../packages/bots;
    dependencies = [
      sources."@arsonar/client-0.4.0"
      sources."@arsonar/common-0.4.0"
      sources."aggregate-error-3.1.0"
      sources."ansi-styles-4.3.0"
      sources."argparse-1.0.10"
      sources."arrify-2.0.1"
      sources."assign-symbols-1.0.0"
      sources."async-exit-hook-2.0.1"
      sources."atomic-sleep-1.0.0"
      sources."base32-encode-1.2.0"
      sources."batch-0.6.1"
      sources."chalk-4.1.2"
      sources."clean-stack-2.2.0"
      sources."codecs-2.2.0"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."commander-5.1.0"
      sources."cross-spawn-7.0.3"
      sources."crypto-hash-1.3.0"
      sources."debug-4.3.2"
      sources."define-property-2.0.2"
      sources."encoding-0.1.13"
      sources."end-of-stream-1.4.4"
      sources."esprima-4.0.1"
      sources."eventsource-git://github.com/frando/eventsource"
      (sources."execa-5.1.1" // {
        dependencies = [
          sources."is-stream-2.0.1"
        ];
      })
      sources."extend-shallow-3.0.2"
      sources."fast-fifo-1.0.0"
      sources."fast-redact-3.0.1"
      sources."fast-safe-stringify-2.0.8"
      sources."find-process-1.4.4"
      sources."fkill-7.2.1"
      sources."flatstr-1.0.12"
      sources."get-stream-6.0.1"
      sources."has-flag-4.0.0"
      sources."human-signals-2.1.0"
      sources."iconv-lite-0.6.3"
      sources."indent-string-4.0.0"
      sources."inherits-2.0.4"
      sources."inspect-custom-symbol-1.1.1"
      sources."is-accessor-descriptor-1.0.0"
      sources."is-buffer-2.0.5"
      sources."is-data-descriptor-1.0.0"
      sources."is-descriptor-1.0.2"
      sources."is-docker-2.2.1"
      sources."is-extendable-1.0.1"
      sources."is-plain-object-2.0.4"
      sources."is-running-2.1.0"
      sources."is-stream-1.1.0"
      sources."is-wsl-2.2.0"
      sources."isexe-2.0.0"
      sources."isobject-3.0.1"
      sources."isomorphic-fetch-2.2.1"
      sources."js-yaml-3.14.1"
      sources."kind-of-6.0.3"
      sources."little-process-box-0.2.3"
      sources."merge-stream-2.0.0"
      sources."mimic-fn-2.1.0"
      sources."ms-2.1.2"
      sources."mutexify-1.3.1"
      sources."nanoassert-2.0.0"
      sources."nanoguard-1.3.0"
      sources."nanoprocess-0.8.5"
      sources."nanoresource-1.3.0"
      sources."nanoresource-pool-0.3.1"
      sources."node-fetch-1.7.3"
      sources."npm-run-path-4.0.1"
      sources."object-path-0.11.5"
      sources."once-1.4.0"
      sources."onetime-5.1.2"
      sources."open-7.4.2"
      sources."original-1.0.2"
      sources."p-finally-2.0.1"
      sources."parse-dat-url-3.0.3"
      sources."path-key-3.1.1"
      sources."pid-port-0.1.1"
      sources."pidtree-0.3.1"
      sources."pidusage-2.0.21"
      sources."pino-6.13.0"
      sources."pino-std-serializers-3.2.0"
      sources."pretty-hash-1.0.1"
      (sources."process-exists-4.1.0" // {
        dependencies = [
          sources."ps-list-6.3.0"
        ];
      })
      sources."ps-list-7.2.0"
      sources."pump-3.0.0"
      sources."querystringify-2.2.0"
      sources."queue-microtask-1.2.3"
      sources."queue-tick-1.0.0"
      sources."quick-format-unescaped-4.0.3"
      sources."randombytes-2.1.0"
      sources."readable-stream-3.6.0"
      sources."regex-not-1.0.2"
      sources."requires-port-1.0.0"
      sources."ret-0.1.15"
      sources."safe-buffer-5.2.1"
      sources."safe-regex-1.1.0"
      sources."safer-buffer-2.1.2"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-3.0.3"
      sources."simple-message-channels-1.2.1"
      sources."simple-rpc-protocol-0.4.1"
      sources."simple-websocket-8.1.1"
      sources."sonic-boom-1.4.1"
      sources."sprintf-js-1.0.3"
      sources."streamx-2.11.1"
      sources."string_decoder-1.3.0"
      sources."strip-final-newline-2.0.0"
      sources."supports-color-7.2.0"
      (sources."taskkill-3.1.0" // {
        dependencies = [
          sources."execa-3.4.0"
          sources."get-stream-5.2.0"
          sources."human-signals-1.1.1"
          sources."is-stream-2.0.1"
        ];
      })
      sources."through2-3.0.2"
      sources."to-data-view-1.1.0"
      sources."to-regex-3.0.2"
      sources."url-parse-1.5.3"
      sources."util-deprecate-1.0.2"
      sources."varint-5.0.2"
      sources."whatwg-fetch-3.6.2"
      sources."which-2.0.2"
      sources."wrappy-1.0.2"
      sources."ws-7.5.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      license = "GPL-3.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
